---
- name: "'sos' role"
  hosts: all
  gather_facts: true  # explicitly gather, required. users may have opted out with 'ansible.cfg' or env vars
  gather_subset: os_family  # selects package candidates for install; names may vary
  roles:
    - name: Configure 'sosreport' w/ extra files and checks
      role: sos
      sos_extras:  # dict keys create files in '/etc/sos/extras.d'; lists are lines/report items
        amdgpu:
          - 'rocm-smi -a'
          - ':/sys/class/drm/card*/device/pp_features'
          - ':/sys/class/drm/card*/device/numa_node'
        cri:
          - 'podman system info'
          - 'docker system info'
        net:
          - 'lldpctl -f keyvalue'
        systemd:
          - 'systemd-analyze critical-chain'
