---
# tasks file for sos

- name: Packages
  become: true
  ansible.builtin.package:
    name: "{{ sos_pkgs[ansible_os_family] }}"

- name: Extras
  become: true
  loop: "{{ (sos_extras | dict2items) | default([]) }}"
  loop_control: { loop_var: entry }
  ansible.builtin.copy:
    dest: "/etc/sos/extras.d/{{ entry.key }}"
    content: "{{ entry.value | join('\n') }}"
    mode: '0644'  # lint; suggested in case umask is restricted
