---
name: ansible-lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master", "release/v*"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
